### PR TITLE
Github

### PR DESCRIPTION
**Pull request by audiracmichelle**

### CODE REVIEW

**Comment by audiracmichelle** [comment]
hey @zpopp, I think the hashed titles have to include the numbering? I think the links are not currently working. Or is that somehow only happening on my end?

**Comment by zpopp** [comment]
> hey @zpopp, I think the hashed titles have to include the numbering? I think the links are not currently working. Or is that somehow only happening on my end?

Thanks @audiracmichelle I think I have corrected the issue now. I also updated the screenshots as the previous ones seemed a bit blurry.

**Comment by audiracmichelle** [comment]
It is looking great!

**Review by zpopp — APPROVED** [review]
Added additional edits for introduction to GitHub. Expanding further to bridge gap between novice and intermediate use could be beneficial as future direction.

**Review by zpopp — APPROVED** [review]

**Comment by zpopp** [comment]
Updated GitHub instructions to divide into Basic Intro and Instructions for Cloning Repositories. Added content and screenshots to allow a non-Git user to create a repo, write ReadMe, and upload code using web interface. Also clarified token steps for cloning.

**Pull request merged**
